[package]
name = "objgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
PrintLib = "1.5.2"
clap = { version = "4.5.4", features = ["derive"] }
object = "0.34.0"
pad = "0.1.6"
